---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: c05d37d4a2d42451bd942a04f753008ff91e456f
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: main
  labels:
    expose: "true"
    app: i-ptg-test-get-ciudades
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-ptg-test-get-ciudades
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-ptg-test-get-ciudades
    provider: fabric8
    group: com.redhat
